+incdir+$PROJ_ROOT/rtl/
$PROJ_ROOT/rtl/shared_library.sv
$PROJ_ROOT/rtl/xocc_interface.sv
$PROJ_ROOT/rtl/data_shift_reg.sv
$PROJ_ROOT/rtl/sys2d.sv
$PROJ_ROOT/rtl/mac_int.v
$PROJ_ROOT/rtl/gemm_axim_top.v
$PROJ_ROOT/rtl/accumulator.sv
$PROJ_ROOT/rtl/ptg_dnn_gemm_ctrl.v
$PROJ_ROOT/rtl/pe.sv
$PROJ_ROOT/rtl/group_dispatch.sv
$PROJ_ROOT/rtl/cu.sv
$PROJ_ROOT/rtl/xocc_decoder.sv
$PROJ_ROOT/rtl/gemm_core_top.v
$PROJ_ROOT/rtl/systolic_array.sv
$PROJ_ROOT/rtl/dpe.sv
$PROJ_ROOT/rtl/mac.sv
$PROJ_ROOT/rtl/mac_fp.v
$PROJ_ROOT/rtl/int8_adder.v
$PROJ_ROOT/rtl/acc.sv
$PROJ_ROOT/rtl/wl_clkgate.v
